# Generated by Django 3.2.4 on 2021-07-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='ref',
        ),
    ]
